# CMake generated Testfile for 
# Source directory: /home/dal/ros1_ws/src/pf_lidar_ros_driver/pf_description
# Build directory: /home/dal/ros1_ws/build_isolated/pf_description
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_pf_description_rostest_tests_test_r2000_bringup.launch "/home/dal/ros1_ws/build_isolated/pf_description/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/dal/ros1_ws/build_isolated/pf_description/test_results/pf_description/rostest-tests_test_r2000_bringup.xml" "--return-code" "/usr/bin/python3 /opt/ros/noetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/dal/ros1_ws/src/pf_lidar_ros_driver/pf_description --package=pf_description --results-filename tests_test_r2000_bringup.xml --results-base-dir \"/home/dal/ros1_ws/build_isolated/pf_description/test_results\" /home/dal/ros1_ws/src/pf_lidar_ros_driver/pf_description/tests/test_r2000_bringup.launch ")
set_tests_properties(_ctest_pf_description_rostest_tests_test_r2000_bringup.launch PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/dal/ros1_ws/src/pf_lidar_ros_driver/pf_description/CMakeLists.txt;25;add_rostest;/home/dal/ros1_ws/src/pf_lidar_ros_driver/pf_description/CMakeLists.txt;0;")
add_test(_ctest_pf_description_rostest_tests_test_r2300_bringup.launch "/home/dal/ros1_ws/build_isolated/pf_description/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/dal/ros1_ws/build_isolated/pf_description/test_results/pf_description/rostest-tests_test_r2300_bringup.xml" "--return-code" "/usr/bin/python3 /opt/ros/noetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/dal/ros1_ws/src/pf_lidar_ros_driver/pf_description --package=pf_description --results-filename tests_test_r2300_bringup.xml --results-base-dir \"/home/dal/ros1_ws/build_isolated/pf_description/test_results\" /home/dal/ros1_ws/src/pf_lidar_ros_driver/pf_description/tests/test_r2300_bringup.launch ")
set_tests_properties(_ctest_pf_description_rostest_tests_test_r2300_bringup.launch PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/dal/ros1_ws/src/pf_lidar_ros_driver/pf_description/CMakeLists.txt;26;add_rostest;/home/dal/ros1_ws/src/pf_lidar_ros_driver/pf_description/CMakeLists.txt;0;")
subdirs("gtest")
