(cl:in-package pf_driver-msg)
(cl:export '(HEADER-VAL
          HEADER
          LAYER_INDEX-VAL
          LAYER_INDEX
          LAYER_INCLINATION-VAL
          LAYER_INCLINATION
          TIMESTAMP_RAW-VAL
          TIMESTAMP_RAW
          RESERVED1-VAL
          RESERVED1
          STATUS_FLAGS-VAL
          STATUS_FLAGS
          SCAN_FREQUENCY-VAL
          SCAN_FREQUENCY
          NUM_POINTS_SCAN-VAL
          NUM_POINTS_SCAN
          NUM_POINTS_PACKET-VAL
          NUM_POINTS_PACKET
          FIRST_INDEX-VAL
          FIRST_INDEX
          FIRST_ANGLE-VAL
          FIRST_ANGLE
          ANGULAR_INCREMENT-VAL
          ANGULAR_INCREMENT
          RESERVED2-VAL
          RESERVED2
          RESERVED3-VAL
          RESERVED3
          RESERVED4-VAL
          RESERVED4
          RESERVED5-VAL
          RESERVED5
))